phpcommerce.payment.gateway.giropay.redirect:
    path:     /payment/giropay/redirect
    defaults: { _controller: PHPCommerceGiropayPaymentBundle:Giropay:redirect }

phpcommerce.payment.gateway.giropay.notify:
    path:     /payment/giropay/notify
    defaults: { _controller: PHPCommerceGiropayPaymentBundle:Giropay:notify }
