imports:
    - { resource: giropay-vendor.yml }
    - { resource: giropay-payment-gateway.yml }

parameters:
    phpcommerce.payment.gateway.giropay.configuration.merchantId:  3609575
    phpcommerce.payment.gateway.giropay.configuration.projectId:   8797
    phpcommerce.payment.gateway.giropay.configuration.secret:      fStSrJZVfQ
