services:
    phpcommerce.payment.gateway.giropay.configuration:
          class:       PHPCommerce\Payment\Service\Gateway\GiropayConfigurationImpl
          calls:
            - [setMerchantId,             ["%phpcommerce.payment.gateway.giropay.configuration.merchantId%"]]
            - [setProjectId,              ["%phpcommerce.payment.gateway.giropay.configuration.projectId%"]]
            - [setSecret,                 ["%phpcommerce.payment.gateway.giropay.configuration.secret%"]]
            - [setNotifyUrl,              ["%app.baseUrl%/gateway/giropay/notify"]]
            - [setRedirectUrl,            ["%app.baseUrl%/gateway/giropay/redirect"]]

    phpcommerce.payment.gateway.giropay.rollback_service:
          class:      PHPCommerce\Payment\Service\Gateway\GiropayRollbackServiceImpl


    phpcommerce.payment.gateway.giropay.hosted_service:
          class:      PHPCommerce\Payment\Service\Gateway\GiropayHostedServiceImpl
          calls:
            - [setConfiguration,          ["@phpcommerce.payment.gateway.giropay.configuration"]]
            - [setGiropayPaymentService,  ["@phpcommerce.payment.vendor.giropay.payment_service"]]

    phpcommerce.payment.gateway.reporting_service:
          class:      PHPCommerce\Payment\Service\Gateway\GiropayReportingServiceImpl
          calls:
            - [setConfiguration,          ["@phpcommerce.payment.gateway.giropay.configuration"]]
            - [setGiropayPaymentService,  ["@phpcommerce.payment.vendor.giropay.payment_service"]]

    phpcommerce.payment.gateway.giropay.configuration_service:
          class:      PHPCommerce\Payment\Service\Gateway\GiropayConfigurationServiceImpl
          tags:
            -  { name: phpcommerce.payment.gateway }
          calls:
            - [setConfiguration,          ["@phpcommerce.payment.gateway.giropay.configuration"]]
            - [setHostedService,          ["@phpcommerce.payment.gateway.giropay.hosted_service"]]
